title = 'Congeladora'
description = 'Congeladora una extensión de tu negocio con una ubicación inmejorable en la Ciudad de México, le ofrecemos el mejor servicio para congelar o conservar tu producto.'
titleSeparator = '|'
thumbnail = 'logo/congeladora.svg'
